= OCP APP DEV WITH RH PAM


== Making Preperations

=== RHSSO

* Installing link:https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_single_sign-on_for_openshift/#using_the_rh_sso_for_openshift_image_streams_and_application_templates[RHSSO 7.2] Templates & Images

	oc login -u system:admin
	cd ./ocp_pam_app_dev
	./Infrastructure/scripts/prepare_env_sso.sh

	# DEPRECATED
	--------------------
	# oc create -f https://github.com/jboss-container-images/redhat-sso-7-openshift-image/blob/sso72-dev/templates/sso72-image-stream.json -n openshift
	# for resource in sso72-image-stream.json \
	#   sso72-https.json \
	#   sso72-mysql-persistent.json \
	#   sso72-mysql.json \
	#   sso72-postgresql-persistent.json \
	#   sso72-postgresql.json
	# do
	#   oc replace -n openshift --force -f \
	#   https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.16/sso/${resource}
	# done


* Run the following command to install the RH-SSO 7.2 OpenShift image streams in the openshift project:

        oc import-image redhat-sso72-openshift:1.0 -n openshift
        oc import-image redhat-sso72-openshift:1.1 -n openshift
        oc import-image redhat-sso72-openshift:1.2 -n openshift

=== Nexus

* *TBD*

=== RHPAM

==== Image Stream

	cd ./ocp_pam_app_dev
	unzip ./resources/rhpam-7.2.0-openshift-templates.zip
	oc create -f ./resources/rhpam72-image-streams.yaml -n openshift

==== Put RHPAM images in place

* *Business Central*: A platform for authoring business assets such as data objects, rules, processes, cases, and planning entities.

	oc import-image my-rhpam-7/rhpam72-businesscentral-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-businesscentral-openshift --confirm -n openshift

* *KIE Server* REST services runtime environment for business assets such as business processes, rules, cases, and planning entities.

	oc import-image my-rhpam-7/rhpam72-kieserver-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-kieserver-openshift --confirm -n openshift

* *KIE (Standalone) Controller*:  A component for managing multiple KIE Servers (Process, Decision, Planning) in manage mode.

	oc import-image my-rhpam-7/rhpam72-controller-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-controller-openshift --confirm -n openshift

* *Smart Router*: Load balancing, unified view on available business assets, and aggregation of responses throughout multiple KIE Servers (Process, Decision, Planning).

	oc import-image my-rhpam-7/rhpam72-smartrouter-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-smartrouter-openshift --confirm -n openshift

* *Business Central Monitoring*: A platform for monitoring and management of business assets.

	oc import-image my-rhpam-7/rhpam72-businesscentral-monitoring-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-businesscentral-monitoring-openshift --confirm -n openshift

==== Insert Templates

	cd ./ocp_pam_app_dev
	oc create -f ./resources/<template-name> -n openshift

==== Custom Tempates

* Template Name:
** location:
** purpose:



== CI/CD PoC Setups

=== Tools project

	oc new-project <YOUR-TOOLS-NAEMSPACE>tools
	
1. create nexus + rh proxy repos

		cd ./ocp_pam_app_dev
		oc login -u <CLUSTER PUBLIC IP> -u <USERNAME> -p <PASSWORD>
		oc project tools
		# oc create -f nexus-dc.yaml -n tools
		./Infrastructure/scripts/setup_nexus.sh <YOUR-TOOLS-NAEMSPACE>tools <CLUSTER PUBLIC URL>192.168.42.21

2. SSO Setp

		oc login -u <CLUSTER PUBLIC IP> -u <USERNAME> -p <PASSWORD>
		oc project tools
		#oc new-app --template=openshift/sso72-x509-https -p APPLICATION_NAME=cgd-sso -p SSO_ADMIN_USERNAME=ssoadmin -p SSO_ADMIN_PASSWORD=ssoadmin720! -l app=sso -n tools
		./Infrastructure/scripts/setup_sso.sh tools FALSE
		
3. jenkins
4. gogs
5. quay.io?


=== DEV Project

* *Business Central* Installation/Configuration:

	cd ./ocp_pam_app_dev
	oc login -u <CLUSTER PUBLIC IP> -u <USERNAME> -p <PASSWORD>
	oc project pam-dev
	oc create -f Infrastructure/templates/rhpam72-authoring-stelios-1.yaml
	./Infrastructure/scripts/setup_DEV_managed.sh <YOUR-DEV-NAMESPACE>pam-dev <YOUR-TOOLS-NAMESPACE>tools

* Create projects at RHPAM Central
* Add <distribution-management> section (see installation/configuration messages)
* *Deploy* from RHPAM Central
* Find Process and execute as executionUser/executionUser123! (externally)
												
=== PROD Project

	cd ./ocp_pam_app_dev
	oc login -u <CLUSTER PUBLIC IP> -u <USERNAME> -p <PASSWORD>
	oc project pam-dev
	oc create -f Infrastructure/templates/rhpam72-prod-stelios-1.yaml
	./Infrastructure/scripts/setup_PROD_managed.sh <YOUR-DEV-NAMESPACE>pam-prod <YOUR-TOOLS-NAMESPACE>tools

* Go to RHPAM Central Monitoring (rhpamadmin/rhpamadmin720)
* Add deployment Unit to correct kieserver cluster
* execute against smartrouter/kieserver directly as executionUser/executionUser123

	

=== ERRORS

==== BC

=== KIESERVER

	








