= OCP APP DEV WITH RH PAM


== Making Preperations

=== RHSSO

* Installing link:https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_single_sign-on_for_openshift/#using_the_rh_sso_for_openshift_image_streams_and_application_templates[RHSSO 7.2] Templates & Images

	for resource in sso72-image-stream.json \
	  sso72-https.json \
	  sso72-mysql-persistent.json \
	  sso72-mysql.json \
	  sso72-postgresql-persistent.json \
	  sso72-postgresql.json
	do
	  oc replace -n openshift --force -f \
	  https://raw.githubusercontent.com/jboss-openshift/application-templates/ose-v1.4.16/sso/${resource}
	done

* Run the following command to install the RH-SSO 7.2 OpenShift image streams in the openshift project:

        oc import-image redhat-sso72-openshift:1.0 -n openshift
        oc import-image redhat-sso72-openshift:1.1 -n openshift
        oc import-image redhat-sso72-openshift:1.2 -n openshift
        oc import-image redhat-sso72-openshift:1.3 -n openshift

=== Nexus

* *TBD*

=== RHPAM

==== Image Stream
	cd ./resources/
	unzip rhpam-7.2.0-openshift-templates.zip
	oc create -f rhpam72-image-streams.yaml

==== Put RHPAM images in place

* *Business Central*: A platform for authoring business assets such as data objects, rules, processes, cases, and planning entities.

	oc import-image my-rhpam-7/rhpam72-businesscentral-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-businesscentral-openshift --confirm

* *KIE Server* REST services runtime environment for business assets such as business processes, rules, cases, and planning entities.

	oc import-image my-rhpam-7/rhpam72-kieserver-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-kieserver-openshift --confirm

* *KIE (Standalone) Controller*:  A component for managing multiple KIE Servers (Process, Decision, Planning) in manage mode.

	oc import-image my-rhpam-7/rhpam72-controller-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-controller-openshift --confirm

* *Smart Router*: Load balancing, unified view on available business assets, and aggregation of responses throughout multiple KIE Servers (Process, Decision, Planning).

	oc import-image my-rhpam-7/rhpam72-smartrouter-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-smartrouter-openshift --confirm

* *Business Central Monitoring*: A platform for monitoring and management of business assets.

	oc import-image my-rhpam-7/rhpam72-businesscentral-monitoring-openshift --from=registry.access.redhat.com/rhpam-7/rhpam72-businesscentral-monitoring-openshift --confirm

==== Insert Templates

   	cd ./resources/templates
	oc create -f <template-name> -n openshift

==== Custom Tempates

* Template Name:
** location:
** purpose:



== CI/CD PoC Setups

=== Tools project

	oc new-project rhpam-tools
	
	1. create nexus + rh proxy repos
	2. SSO

		oc new-app template=sso72-https -p APPLICATION_NAME=gcd -p SSO_ADMIN_USERNAME=ssoadmin -p SSO_ADMIN_PASSWORD=ssoadmin720!

	3. jenkins
	4. gogs
	5. quay.io?


=== DEV Project

* *Business Central* Installation/Configuration:

	create the clients for Red Hat Process Automation Manager within RH-SSO,

oc new-app --template=openshift/rhpam72-authoring \
                        -p BUSINESS_CENTRAL_HTTPS_SECRET=businesscentral-app-secret  \
                        -p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret \
                        -p APPLICATION_NAME=gcd \
                        -p BUSINESS_CENTRAL_HTTPS_NAME=businesscentral \
                        -p BUSINESS_CENTRAL_HTTPS_PASSWORD=mykeystorepass \
                        -p BUSINESS_CENTRAL_HTTPS_KEYSTORE=bckeystore.jks \
                        -p KIE_SERVER_HTTPS_NAME=kieserver \
                        -p KIE_SERVER_HTTPS_PASSWORD=mykeystorepass  \
			-p KIE_SERVER_HTTPS_KEYSTORE==kiekeystore.jks
                        -p KIE_ADMIN_USER=rhpamadmin \
                        -p KIE_ADMIN_PWD=rhpamadmin720! \
                        -p KIE_SERVER_USER=executionUser \
                        -p KIE_SERVER_PWD=executionUser123! \
                        -p KIE_SERVER_CONTROLLER_USER=controllerUser \
                        -p KIE_SERVER_CONTROLLER_PWD=controllerUser123! \
                        -p MAVEN_REPO_URL=http://nexus-nexus.bpmapps.grupocgd.com/repository/maven-public \
                        -p MAVEN_REPO_USERNAME=nexus \
                        -p MAVEN_REPO_PASSWORD=nexus123 \
                        -p MAVEN_REPO_ID=maven-public \
                        -p SSO_URL=https://gcd-sso-nexus.bpmapps.grupocgd.com \
                        -p SSO_REALM=Master \
                        -p BUSINESS_CENTRAL_SSO_CLIENT=gcd-rhpamcentral \
                        -p KIE_SERVER_SSO_CLIENT=gcd-kieserver \
                        -p SSO_USERNAME=ssoadmin \
                        -p SSO_PASSWORD=ssoadmin720! \
                        -p SSO_DISABLE_SSL_CERTIFICATE_VALIDATION=true -l app=bc

	oc new-app -f rhpam72-authoring \
			-p BUSINESS_CENTRAL_HTTPS_SECRET=businesscentral-app-secret  \
			-p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret \
			-p APPLICATION_NAME=gcd \
			-p BUSINESS_CENTRAL_HTTPS_NAME=businesscentral \
			-p BUSINESS_CENTRAL_HTTPS_PASSWORD=mykeystorepass \
			-p KIE_SERVER_HTTPS_NAME=kieserver \
			-p KIE_SERVER_HTTPS_PASSWORD=mykeystorepass  \
			-p KIE_ADMIN_USER=rhpamadmin \
			-P KIE_ADMIN_PWD=rhpamadmin720! \
			-p KIE_SERVER_USER=executionUser \
			-p KIE_SERVER_PWD=executionUser123! \
			-p KIE_SERVER_CONTROLLER_USER=controllerUser \
			-p KIE_SERVER_CONTROLLER_PWD=controllerUser123! \
			-p MAVEN_REPO_URL=http://nexus-nexus.bpmapps.grupocgd.com/repository/maven-public \
			-p MAVEN_REPO_USERNAME=nexus \
			-p MAVEN_REPO_PASSWORD=nexus123 \
			-p MAVEN_REPO_ID=maven-public \
			-p SSO_URL=https://gcd-sso-nexus.bpmapps.grupocgd.com \
			-p SSO_REALM=Master \
			-p BUSINESS_CENTRAL_SSO_CLIENT=gcd-rhpamcentral \
			-p KIE_SERVER_SSO_CLIENT=gcd-kieserver \
			-p SSO_USERNAME=ssoadmin \
			-p SSO_PASSWORD=ssoadmin720! \									
			-p SSO_DISABLE_SSL_CERTIFICATE_VALIDATION=true \



	oc new-app -f rhpam72-authoring \
			-p BUSINESS_CENTRAL_HTTPS_SECRET=businesscentral-app-secret  \
			-p KIE_SERVER_HTTPS_SECRET=kieserver-app-secret \
			-p APPLICATION_NAME=gcd \
			-p BUSINESS_CENTRAL_HTTPS_NAME=businesscentral \
			-p BUSINESS_CENTRAL_HTTPS_PASSWORD=mykeystorepass \
			-p KIE_SERVER_HTTPS_NAME=kieserver \
			-p KIE_SERVER_HTTPS_PASSWORD=mykeystorepass  \
			-p KIE_ADMIN_USER=rhpamadmin \
			-P KIE_ADMIN_PWD=rhpamadmin720! \
			-p KIE_SERVER_USER=executionUser \
			-p KIE_SERVER_PWD=executionUser123! \
			-p KIE_SERVER_CONTROLLER_USER=controllerUser \
			-p KIE_SERVER_CONTROLLER_PWD=controllerUser123! \
			-p  \
			-p  \
			-p  \
			-p  \
			-p  \
			-p  \
			-p MAVEN_REPO_URL=http://nexus-nexus.bpmapps.grupocgd.com/repository/maven-public \
			-p MAVEN_REPO_USERNAME=nexus \
			-p MAVEN_REPO_PASSWORD=nexus123 \
			-p MAVEN_REPO_ID=maven-public \
			-p  \
			-p SSO_URL=https://gcd-sso-nexus.bpmapps.grupocgd.com \
			-p SSO_REALM=Master \
			-p BUSINESS_CENTRAL_SSO_CLIENT=gcd-rhpamcentral \
		[REMOVE -p BUSINESS_CENTRAL_SSO_SECRET= \
		[REMOVE]-p BUSINESS_CENTRAL_HOSTNAME_HTTP=http://gcd-rhpamcentr-gcd-dev.bpmapps.grupocgd.com/ \
		[REMOVE]-p BUSINESS_CENTRAL_HOSTNAME_HTTPS=https://secure-gcd-rhpamcentr-gcd-dev.bpmapps.grupocgd.com/
			-p KIE_SERVER_SSO_CLIENT=gcd-kieserver \
		[REMOVE -p KIE_SERVER_SSO_SECRET= \		
		[REMOVE]-p KIE_SERVER_HOSTNAME_HTTP= \
		[REMOVE]-p KIE_SERVER_HOSTNAME_HTTPS= \									
			-p SSO_USERNAME=ssoadmin \
			-p SSO_PASSWORD=ssoadmin720! \									
			-p SSO_DISABLE_SSL_CERTIFICATE_VALIDATION=true \
			-p  \									
			-p  \
			-p  \									
							

							


=== PROD Project
re-service" => "management"),
    ("security-realm" => "ApplicationRealm")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.core.management.security.realm.ApplicationRealm.key-manager" => "Failed to start service
    Caused by: java.lang.IllegalStateException: org.jboss.msc.service.StartException in anonymous service: WFLYDM0086: The KeyStore can not be found at /etc/kieserver-secret-volume/keystore.jks
    Caused by: org.jboss.msc.service.StartException in anonymous service: WFLYDM0086: The KeyStore can not be found at /etc/kieserver-secret-volume/keystore.jks"}}
19:37:38,461 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 44) WFLYSRV0010: Deployed "ROOT.war" (runtime-name : "ROOT.war")
19:37:38,468 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.core.management.security.realm.ApplicationRealm.key-manager: Failed to start service
WFLYCTL0448: 4 additional services are down due to their dependencies being missing or failed
19:37:38,668 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
19:37:38,674 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
19:37:38,674 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
19:37:38,674 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: JBoss EAP 7.2.0.GA (WildFly Core 6.0.11.Final-redhat-00001) started (with errors) in 31129ms - Started 365 of 722 services (7 services failed or missing dependencies, 477 services are lazy, passive or on-demand)




T.war/WEB-INF/lib/jaxb-core-2.3.0.jar  does not point to a valid jar for a Class-Path reference.
19:39:04,724 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry jaxb-core.jar in /opt/eap/standalone/deployments/ROOT.war/WEB-INF/lib/jaxb-impl-2.3.0.jar  does not point to a valid jar for a Class-Path reference.
19:39:05,175 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("add") failed - address: ([
    ("core-service" => "management"),
    ("security-realm" => "ApplicationRealm")
]) - failure description: {"WFLYCTL0080: Failed services" => {"org.wildfly.core.management.security.realm.ApplicationRealm.key-manager" => "Failed to start service
    Caused by: java.lang.IllegalStateException: org.jboss.msc.service.StartException in anonymous service: WFLYDM0086: The KeyStore can not be found at /etc/businesscentral-secret-volume/keystore.jks
    Caused by: org.jboss.msc.service.StartException in anonymous service: WFLYDM0086: The KeyStore can not be found at /etc/businesscentral-secret-volume/keystore.jks"}}
19:39:05,187 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 44) WFLYSRV0010: Deployed "ROOT.war" (runtime-name : "ROOT.war")
19:39:05,199 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service org.wildfly.core.management.security.realm.ApplicationRealm.key-manager: Failed to start service
WFLYCTL0448: 4 additional services are down due to their dependencies being missing or failed
19:39:05,343 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
19:39:05,350 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
19:39:05,351 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
19:39:05,351 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: JBoss EAP 7.2.0.GA (WildFly Core 6.0.11.Final-redhat-00001) started (with errors) in 47714ms - Started 348 of 705 services (7 services failed or missing dependencies, 475 services are lazy, passive or on-demand)

	








